### ISSUE TITLE
Gibson fails when disabling all UI components while rendering RGB image to the agent

### ISSUE THREAD

**Issue by glewis17** [StanfordVL/GibsonEnv#44]
Below error message obtained when running `examples/demo/play_husky_camera.py`:

![image](https://user-images.githubusercontent.com/5433136/46182094-9cf88280-c27e-11e8-95c5-3b4be8e7065c.png)

`examples/configs/play/play_husky_camera.py`:

`...`
`display_ui: false`
`show_diagnostics: false`
`ui_num: 0`
`ui_components: []`
`...`
`output: [nonviz_sensor, rgb_filled]`
`...`

**Comment by hzyjerry** [comment]
Hi @glewis17 thanks for finding this issue. It is due to improper data loading in this configuration.

We have fixed this in master branch. Another thing is that by setting `display_ui: false`, you will not see Gibson's pygame-based UI, but will still see pybullet's native UI.

If you'd like to completely hide UI, you can set `mode: headless` as following:


```...
display_ui: false
show_diagnostics: false
ui_num: 0
ui_components: []
...
output: [nonviz_sensor, rgb_filled]
...
mode: headless
...```

**Comment by JiaXuanWang** [comment]
Hi @hzyjerry I have modified `play_husky_camera.yaml` as you said. But it still doesn't work. When I run `python examples/demo/play_husky_camera.py`, it stops as follows:
![image](https://user-images.githubusercontent.com/38659298/54338286-6962b680-466c-11e9-8c59-68a35495ea46.png)
I found it stopped at the line in `gibson/core/render/pcrender.py`:
`mist_msg = self.socket_mist.recv()`
Can you give me some advice to solve this problem?

**Comment by mathildecaron31** [comment]
Hi @JessieWang-wjx , could you fix your problem ? I'm facing the same issue
